### ISSUE TITLE
Спектр генерируемых значений

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/Zoo_and_Animals#1]
Вот тут 

``` java
String color = col_arr[gen.nextInt(5)];
String gender = gender_arr[gen.nextInt(2)];
```

Скрывается потенциальная ошибка (если кто-то изменит соответствующие массивы). При случайной генерации из массива есть смысл делать так:

``` java
array[random.nextInt(array.length)]
```

Проверьте генерацию в других массивах тоже :)

**Comment by escos** [comment]
Все, исправил.
