### ISSUE TITLE
Опционально, но полезно. Форматирование строк

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/Zoo_and_Animals#2]
Там, где вы используете конструкции типа

``` java
System.out.println((i + 1) + " сбежавший представитель зоопарка - это " + animal_mass[i].kind + " животное - " + animal_mass[i].name+".");
```

Обычно используют форматирование строк. Это то, когда мы пишем `printf` и проценты. Это будет читаемее и удобнее. В целом Идея сама умеет конвертировать это в форматирование (по alt+enter), однако вам очень пригодится, если вы разберетесь сами, как это сделать.

Документация тут:
https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html
Примеры указаны с форматтером, при печати в System.out у нас есть встроенные методы, которые внутри форматируют, им нужны тольк строка и список аргументов через запятую (`System.out.printf(string_format, arg0, arg1,arg2)`).
Например,

``` java
System.out.printf("Numbers %d %d %d are %s numbers!", 6, 28, 496, "perfect");
```

**Comment by escos** [comment]
Я знаком с форматируемым выводом, уже использовал в предыдущих программах. Где нужно, исправил на printf.
