### ISSUE TITLE
Типы животных явно хотят в константы

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/Zoo_and_Animals#3]
Типы животных (травоядное и хищное) хотят в константы. :)

Дело в том, что если вы где-то ошибетесь в написании, то код перестанет работать.
Если есть желание поработать над кодом дальше, можете посмотреть на enums, это то, что используется, если хочется ограничить типы до определенного круга и не использовать boolean. Тут можно больше двух значений. [Вот тут статья о том, что это](https://stokito.wordpress.com/2011/04/05/%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D1%8B-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-enum-%D0%B8-static-import%D1%8B-%D0%B2-java/)

**Comment by escos** [comment]
Вроде немного разобрался с enum. Добавил новый класс с двумя константами.

**Comment by anastasiya-solodkaya** [comment]
Хм, вообще с enums работают не совсем так. Скорее нужно создать Animals.Kinds (с большой буквы обязательно, у вас сейчас с маленькой) и поле использовать этого типа Animal.Kinds. То, что есть сейчас - это когда enums используются вместо констант, и переопределяется toString.
Метод toString рекомендуется пользовать исключительно для отладки, кстати. Не стоит его переопределять у enums

**Comment by escos** [comment]
По поводу констант есть вопросы...
