### ISSUE TITLE
Сравнение строк

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/Zoo_and_Animals#4]
Сравнение строк типа
`name == "Петя"` в общем случае сработает неправильно. Это сравнение по ссылке, потому что строка - это объект. Если вы хотите сравнивать два объекта, то вам нужен метод **equals** или какой-то другой, который подходит и есть в соответствующем классе.

Ваш код работает потому, что у вас простой случай и java создает только один экземпляр со значением "травоядное", например, и использует его везде. Это особенность именно java, и ей не стоит пользоваться. Она есть на слайжах со строками, кстати. Там чуть подробнее. Если бы не было этой особенности, то 

``` java
String s1 = "травоядное";
String s2 = "травоядное";
System.out.println(s1 == s2);
```

вернул бы **false**. Но у нас тут **true**.

Вот тут может быть станет чуть понятнее, как оно работает. В любом случае, вам стоит всегда использовать equals вместо == для объектов (кроме enums)

``` java
String s1 = "abc";
String s2 = "abc";
String s3 = "a" + "bc";
String s4 = "a";
String s5 = s4 + "bc";
String s6 = new String("abc");
String s7 = s2 + "";

System.out.printf("(s1 vs s2) %1$s == %2$s ? %3$s\t%1$s equals %2$s ? %4$s %n", s1, s2, s1 == s2, s1.equals(s2));
System.out.printf("(s1 vs s3) %1$s == %2$s ? %3$s\t%1$s equals %2$s ? %4$s %n", s1, s3, s1 == s3, s1.equals(s3));
System.out.printf("(s1 vs s5) %1$s == %2$s ? %3$s\t%1$s equals %2$s ? %4$s %n", s1, s5, s1 == s5, s1.equals(s5));
System.out.printf("(s1 vs s6) %1$s == %2$s ? %3$s\t%1$s equals %2$s ? %4$s %n", s1, s6, s1 == s6, s1.equals(s6));
System.out.printf("(s1 vs s7) %1$s == %2$s ? %3$s\t%1$s equals %2$s ? %4$s %n", s1, s7, s1 == s7, s1.equals(s7));
```

**Comment by escos** [comment]
Заменил все равенства/неравенства на equals.

**Comment by anastasiya-solodkaya** [comment]
Теперь у вас там enums, а их сравнивать через == можно и нужно как раз :)

**Comment by anastasiya-solodkaya** [comment]
Таки я не права, оказывается, вы в поле все еще строку испольуете, так что там нужен equals. Это я закрываю, посмотрите комментарий про enums. :)
