### ISSUE TITLE
По поводу стиля

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/Zoo_and_Animals#5]
Название `herbivoreSort` намекает, что там должны быть отсортированные травоядные. Но сортировки там нет. :)
Если речь идет об отделении их от хищных, то там будет не sort, а separate 

Запись Animal arr[], но непривычна, в джава обычно используется запись Animal[] arr

**Comment by escos** [comment]
Название заменил согласно вашей рекомендации, а также исправил запись Animal arr[].

**Comment by anastasiya-solodkaya** [comment]
А зачем в том же методе count? У вас же есть herbalName (кстати странное название с т.з. английског оязыка), и у него можно просто взять size.

**Comment by anastasiya-solodkaya** [comment]
Массивы у вас называются по типу gender_arr.

Вообще в java не рекомендуется использовать такие названия, это не java-стиль.
Как бы я назвала?
availableGenders
genders
gendersArray

как-то так. 
Но подчеркивания - точно не camelCase, и являются очень нежелательными.
Вот тут есть конвенция от Оракла, как называть все в java:
{http://www.oracle.com/technetwork/java/codeconventions-135099.html)

**Comment by escos** [comment]
Исправил названия и убрал count
